### PR TITLE
Initializes all_group to be an empty array

### LINKED ISSUE #48: Bug: Running terraform inventory on empty tfstate returns invalid inventory
## Context

I define a `cluster-name` for some infrastructure I'm provisioning in aws. Before I run `terraform apply` I want to run `terraform destroy` on that cluster-name to make sure that any previous/existing infrastructure is cleaned up before I create new infrastructure. 

## Bug
If I pull tfstate for `cluster-name` that does not exist and then try to run an ansible playbook I get the following error: 

```
ERROR! The file /usr/local/bin/terraform-inventory is marked as executable, but failed to execute correctly. If this is not supposed to be an executable script, correct this with `chmod -x /usr/local/bin/terraform-inventory`.
You defined a group "all" with bad data for the host list:
 {u'hosts': None, u'vars': {<vars here>}}
'utf8' codec can't decode byte 0x80 in position 24: invalid start byte
'utf8' codec can't decode byte 0x80 in position 24: invalid start byte
```

If I run 

`/usr/local/bin/terraform-inventory --list <empty-tfstate> | jq .`

I get
```
{
  "all": {
    "hosts": null,
    "vars": {
      <vars here>
    }
  }
}
```

If I write this to a file and point ansible to it directly I get: 

```
ERROR! 'NoneType' object is not iterable
./test-inventory:2: Expected key=value host variable assignment, got: {
```

If I change the `null` field to an empty json array as below: 
```
{
  "all": {
    "hosts": [], 
    "vars": {
      <vars here>
    }
  }
}
```

And then run ansible with this file it runs as expected.

### PR DESCRIPTION
**Pull request by schauhan19**
Fixes #48.

### CODE REVIEW

File: cli.go [hunk 1]
```diff
@@ -27,7 +27,7 @@ func appendUniq(strs []string, item string) []string {
 
 func gatherResources(s *state) map[string]interface{} {
 	groups := make(map[string]interface{}, 0)
-	all_group := allGroup{Vars: make(map[string]interface{})}
+	all_group := allGroup{Vars: make(map[string]interface{}, 0), Hosts: make([]string, 0)}
```
Comment (adammck) [inline cli.go]: The size parameter is unnecessary when making a map.

**Comment by adammck** [comment]
Great, thanks for the patch! Looks good to me, other than the very minor nit above.
